Optimize CloudBuild performance + document cache architecture

diff --git a/cloudbuild_sub_separate_plugin.yaml b/cloudbuild_sub_separate_plugin.yaml
--- a/cloudbuild_sub_separate_plugin.yaml
+++ b/cloudbuild_sub_separate_plugin.yaml
@@ -1,17 +1,21 @@
 steps:
-  - name: 'golang:1.25'
-    id: 'go-test'
+  - name: 'golang:1.25-alpine'
+    id: 'go-build-and-test'
     args:
       - '-c'
       - |
+        set -e  # Exit immediately if any command fails
+        apk add git make --no-cache
+        # Configure go to use proxy for faster module downloads
+        export GOPRIVATE="github.com/pierrec,google.golang.org"
+        export GOPROXY="https://proxy.golang.org"
+        export GOSUMDB="sum.golang.org"
+        # Download dependencies once (cached for both test and build)
+        echo "Downloading Go modules via proxy..."
+        go mod download
+        # Run tests with race detection
         go test -v -race
-    entrypoint: /bin/sh
-  - name: 'golang:1.25'
-    id: 'go-build'
-    waitFor: ['go-test']
-    args:
-      - '-c'
-      - |
+        # Build plugin (only runs if tests pass due to set -e)
         make build VERSION=$TAG_NAME-$BUILD_ID
         cp vault/plugins/vault-plugin-aead docker/vault-plugin-aead
     entrypoint: /bin/sh
@@ -22,7 +26,7 @@ steps:
       - 'P_VERSION=$TAG_NAME-$BUILD_ID'
       - 'P_NAME=${_PLUGIN_NAME}'
       - 'FQ_BASE_IMAGE=${_FQ_BASE_IMAGE}'
-    waitFor: ['go-build']
+    waitFor: ['go-build-and-test']
     args:
       - build
       - '--build-arg'
@@ -58,4 +62,5 @@ options:
     - 'GOOS=linux'
     - 'GOARCH=amd64'
     - 'TAG_NAME=$TAG_NAME'
-    - 'GOPROXY=direct'
+    # GOPROXY removed - will use default proxy.golang.org for faster module downloads
+    # Private repos still bypass proxy via GOPRIVATE setting above
